# Generated by Django 5.0.3 on 2024-03-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="read_by",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
