# Generated by Django 5.0.3 on 2024-03-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="profile_image",
            field=models.ImageField(
                default="profile_image/default__person.jpg", upload_to="profile_image/"
            ),
        ),
    ]
