# Generated by Django 5.0.3 on 2024-03-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0002_alter_blogpost_read_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="profile_image",
            field=models.ImageField(
                default="default__person.jpg", upload_to="profile_images"
            ),
        ),
    ]
