# Generated by Django 5.0.3 on 2024-03-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0003_alter_author_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="description",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=25),
        ),
    ]
