# Generated by Django 5.0.3 on 2024-03-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0004_alter_blogpost_description_alter_blogpost_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
