# Generated by Django 5.0.3 on 2024-03-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0005_alter_blogpost_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
